#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    echo "Uninstall a homebrew formula and any remaining unused dependencies."
    echo "  ${0} <FORMULA>"
    exit 1
fi

formula=${1}
brew uninstall ${formula}

# this must happen after the initial uninstall
globaldeps=$(echo -e "$(brew list)\n$(brew leaves)" | sort | uniq -u)
unusedformuladeps=$(echo -e "${globaldeps}\n$(brew deps ${formula})" | sort | uniq -d)
brew uninstall ${unusedformuladeps}

# uninstall secondary deps
secondaryformuladeps=$(echo -e "$(brew leaves)\n$(brew deps ${formula})" | sort | uniq -d)
brew uninstall ${secondaryformuladeps}
