#!/usr/bin/env bash
#  This helps the OOMKiller issues with small DigitalOcean VPS

dd if=/dev/zero of=/swapfile bs=1024 count=1048576
chmod 0600 /swapfile
chown root.root /swapfile
mkswap /swapfile
swapon /swapfile
echo "/swapfile swap swap defaults 0 0" >> /etc/fstab
