#!/bin/bash

name=${GIT_NAME-"Dustin Chapman"}
email=${GIT_EMAIL}

cat << EOF
[user]
	name = ${name}
	email = ${email}
[color]
	ui = auto
	interactive = auto
[alias]
	alias = "!f() { git config --global alias.\${1} \"\${2}\"; }; f"
	aliases = !git config --list | grep alias | cut -c 7-
	# diff
	d = diff --color-words
	dsg = diff --staged --color-words
	dr = "!f() { git diff --color-words \${1-HEAD}^..\${1-HEAD}; }; f"
	drr = "!f() { git diff --color-words \${1}..\${2-HEAD}; }; f"
	dst = "!f() { git diff --stat --color-words \${1-HEAD}^..\${1-HEAD}; }; f"
	dstr = "!f() { git diff --stat --color-words \${1}..\${2-HEAD}; }; f"
	# add and unstage
	a = !git add . && git status
	au = !git add -u && git status
	aa = !git add . && git add -u && git status
	un = !git reset HEAD && git status
	# branches and checkouts
	bv = branch -avv
	co = checkout
	ct = checkout -t
	del = "!f() { git branch -D \${1} && git push \${2-origin} --delete \${1}; }; f"
	delm = "!f() { git branch --merged | egrep -v \"(^\\\\*|master|dev)\" | xargs -I % sh -c \"git branch -D % && git push \${1-origin} --delete %\"; }; f"
	prune = fetch --all --prune
	# status
	s = status
	si = status --ignored
	# stash
	sts = stash save
	stsp = stash save --patch
	stsu = stash save --include-untracked
	stl = stash list
	stsh = "!f() { git stash show stash^{/$*} --patch --color-words; }; f"
	sta = "!f() { git stash apply stash^{/$*}; }; f"
	std = "!f() { git stash drop stash@{${1-0}}; }; f"
	stp = "!f() { git stash pop stash@{${1-0}}; }; f"
	# commit
	c = commit
	cm = commit -m
	count = rev-list HEAD --count
	# pull and push
	pn = "!f() { git push -u \${1-origin} \$(git rev-parse --abbrev-ref HEAD); }; f"
	# log
	glog = log --graph
	l = log --graph --pretty=format:'%C(yellow)%h%C(cyan)%d%Creset %s %C(white)- %C(green)%an%C(white), %ar%Creset'
	ll = log --stat --abbrev-commit
	# files
	f = !git ls-tree --full-tree -r HEAD
	fc = !git ls-tree --full-tree -r HEAD | wc -l
	# server
	sro = daemon --verbose --export-all --base-path=.git --reuseaddr --strict-paths .git/
	srw = daemon --base-path=. --export-all --enable=receive-pack --reuseaddr --informative-errors --verbose
[core]
	pager = less -+ -FRX
[merge]
	tool = vimdiff
	conflictstyle = diff3
[mergetool]
	prompt = false
EOF
