#!/usr/bin/env bash

: ${TYPE:="ed25519"}
# ignored unless TYPE is rsa
: ${BITS:="4096"}

: ${REMOTE:=""}
: ${NAME:="$(whoami)"}
: ${LOCATION:="$(hostname -s)"}
: ${DIRECTORY:="${HOME}/.ssh"}

read -s -p "Passphrase: " passphrase; echo
read -s -p "Retype passphrase: " repassphrase; echo
if [ -z "${passphrase}" ]; then
    echo "You should know better..."
elif [ ${passphrase} != ${repassphrase} ]; then
    echo "Retyped passphrase did not match!"
    exit 1
fi

[ ${LOCATION} ] \
    && description="${NAME}@${LOCATION}" \
    || description="${NAME}"
output="${DIRECTORY}/${description}"
puboutput="${output}.pub"

[ -f ${puboutput} ] \
    && echo "key already exists" \
    || ssh-keygen -b ${BITS} -t ${TYPE} -P "${passphrase}" -C "${description}" -f "${output}"

[ ${REMOTE} ] && [ `which ssh-copy-id` ] \
    && ssh-copy-id -i ${puboutput} ${REMOTE} \
    || echo "cannot copy to remote"

echo "To use your key: 'ssh -i ${output} ${REMOTE}'"
