#!/usr/bin/env bash

remote=${1-""}
name=${2-`whoami`}
location=${3-`hostname -s`}
directory=${4-"${HOME}/.ssh"}

read -s -p "Passphrase: " passphrase; echo
read -s -p "Retype passphrase: " repassphrase; echo
if [ -z "${passphrase}" ]; then
    echo "You should know better..."
elif [ ${passphrase} != ${repassphrase} ]; then
    echo "Retyped passphrase did not match!"
    exit 1
fi

[ ${location} ] \
    && description="${name}@${location}" \
    || description="${name}"
output="${directory}/${description}"
puboutput="${output}.pub"

bits=4096
type="rsa"

[ -f ${puboutput} ] \
    && echo "key already exists" \
    || ssh-keygen -b ${bits} -t ${type} -P "${passphrase}" -C "${description}" -f "${output}"

[ ${remote} ] && [ `which ssh-copy-id` ] \
    && ssh-copy-id -i ${puboutput} ${remote} \
    || echo "cannot copy to remote"

echo "To use your key: 'ssh -i ${output} ${remote}'"
