#!/bin/bash

src=${2-"${HOME}/dev/bins"}
dst=${3-"${HOME}/bin"}

mkdir -p ${dst}

for path in $1; do
  if [[ $(uname) = "Darwin" ]]; then
    pushd ${dst}
    find -L "${src}/${path}" -type f -exec basename {} \; | \
      xargs -I % ln -sv ${src}/%
    popd
  else
    find -L "${src}/${path}" -type f -exec ln -rsvt ${dst} {} \;
  fi
done
