#!/usr/bin/env bash
# remove all docker containers and images
# thanks, http://techoverflow.net/blog/2013/10/22/docker-remove-all-images-and-containers/

# Delete all containers
docker rm -f $(docker ps -a -q)

# Delete all images
docker rmi -f $(docker images -q)
