#!/bin/bash

#  Easy spf13-vim clean/install (not yet) or check/update.

cmd=${1-""}

defaultdir="${HOME}/.spf13-vim-3"
basedir="$(dirname ${defaultdir})"
toremove="${defaultdir} ${basedir}/.vimrc* ${basedir}/.vimbackup* ${basedir}/.vim-*"

function gotodir() {
    pushd ${defaultdir} > /dev/null
    if [ "$(pwd)" != "${defaultdir}" ]; then
        echo "Nothing there! Run the install command first."
        exit 1
    fi
}

case "${cmd}" in
    check)
        gotodir && \
        git remote update && \
        git status -uno && \
        popd > /dev/null
        exit "$?"
        ;;
    clean)
        rm -rf ${toremove}
        ;;
    install)
        sh <(curl -L https://j.mp/spf13-vim3) && \
        echo "let g:spf13_bundle_groups=['general', 'neocomplete', 'programming', 'ruby', 'python', 'go', 'javascript', 'html', 'misc', 'writing' ]" > ${basedir}/.vimrc.before.local && \
        # is vim-go flip-flopping on the formatter it uses? stick to goimports please...
        echo 'let g:go_fmt_command = "goimports"' > ${basedir}/.vimrc.local && \
        # will need mercuiral installed for goimports to install
        echo -e "Mercuial is $(which hg >/dev/null 2>&1 && echo '' || echo 'not ')installed." && \
        vim +BundleInstall! +qall
        exit "$?"
        ;;
    update)
        gotodir && \
        git pull && \
        echo "let g:spf13_bundle_groups=['general', 'neocomplete', 'programming', 'ruby', 'python', 'go', 'javascript', 'html', 'misc', 'writing' ]" > ${basedir}/.vimrc.before.local && \
        vim +BundleInstall! +BundleClean +qall && \
        popd > /dev/null
        exit "$?"
        ;;
    *)
        echo "  check"
        echo "  clean   (removes $(echo ${toremove} | sed s@${basedir}\/@@g ))"
        echo "  install (overwrites .vimrc.before.local .vimrc.local)"
        echo "  update"
        ;;
esac

